name: pangeo
channels:
  - conda-forge
dependencies:
  # core scipy packages
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray
  - sparse
  - sympy
  # data science stuff
  - scikit-image
  - scikit-learn
  - dask-ml
  - tensorflow
  - keras
  - pytorch-cpu
  # pyviz
  - holoviews
  - panel
  - geoviews
  - hvplot
  - geoviews
  - datashader
  - seaborn
  - altair
  - descartes
  - folium
  - vega
  - vega_datasets
  - palettable
  - cmocean
  # geospatial
  - iris
  - cartopy
  - basemap
  - geopandas
  - rasterio
  - netcdf4
  - erddapy
  - pydap
  - h5py
  - h5netcdf
  - regionmask
  - rio-cogeo
  # geoscience-related
  - climlab
  - metpy
  - satpy
  - gsw
  - eofs
  - esmpy
  - xesmf
  - windspharm
  # intake-related
  - intake
  - intake-xarray
  - intake-esm
  - fsspec
  - intake-stac
  # zarr-related
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - gcsfs
  - s3fs
  - tiledb-py
  # jupyter-related
  - ipyleaflet
  # xarray-related
  - xgcm
  - xrft
  - xhistogram
  - xlrd
  # - xrviz  # waiting on hvplot release
  - climpred
  - pytide
  - pyinterp
  # misc
  - python-wget
  - prefect
  - pip
  - pip:
    - graphviz
