# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: pangeo
channels:
  - conda-forge
dependencies:
  - jupyterlab=1.*
  - dask=2.*
  - aask-kubernetes=0.9
  - tornado=6.*
  - jupyter-server-proxy
  - bokeh
  - graphviz
  - pip
  - pip:
    - git+https://github.com/ian-r-rose/dask-labextension.git@de-asyncify#egg=dask_labextension
